require:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/{rails,rake,bundle}'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'app/mailers/**/*'
Layout/LineLength:
  Exclude:
    - 'initializers/**/*'
RSpec/MultipleExpectations:
  Max: 8
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/NestedGroups:
  Max: 4

Metrics/MethodLength:
  Enabled: false
