name: RuboCop

on: [push, pull_request]

jobs:
  rubocop-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
    - name: Install dependencies
      run: bundle install
    - name: Run RuboCop
      run: bundle exec rubocop

